import turtle
turtle.speed(100)


# Стена дома
turtle.penup()
turtle.left(90)
turtle.goto(-150, -70)
turtle.pendown()
turtle.pencolor('orange')
turtle.fillcolor('orange')
turtle.begin_fill()
turtle.forward(120)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(150)
turtle.end_fill()
turtle.penup()


# Дверь
turtle.goto(-60, -70)
turtle.pendown()
turtle.pencolor('white')
turtle.fillcolor('brown')
turtle.begin_fill()
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()
turtle.penup()

# Крыша
turtle.goto(-170, 50)
turtle.pendown()
turtle.pencolor('brown')
turtle.fillcolor('red')
turtle.begin_fill()
turtle.goto(-70, 130)
turtle.goto(20, 50)
turtle.goto(-170, 50)
turtle.end_fill()
turtle.penup()

# Солнце
turtle.goto(220, 130)
turtle.right(90)
turtle.pencolor('orange')
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()
turtle.penup()

# Земля
turtle.pencolor('brown')
turtle.goto(0, -70)
turtle.left(90)
turtle.pendown()
turtle.forward(260)
turtle.right(180)
turtle.forward(520)
turtle.penup()

# Левый забор
turtle.pencolor('brown')
turtle.goto(-240, -70)
turtle.left(90)
turtle.pendown()
for i in range(3):
    turtle.fillcolor('yellow')
    turtle.begin_fill()
    turtle.forward(40)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(40)
    turtle.end_fill()
    turtle.left(180)
turtle.penup()

# дерево (ствол)
turtle.pencolor('orange')
turtle.goto(130, -70)
turtle.pendown()
turtle.fillcolor('brown')
turtle.begin_fill()
turtle.forward(40)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(40)
turtle.end_fill()
turtle.penup()

# Дерево (листва)
turtle.goto(135, -15)
turtle.pencolor('dark green')
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.dot(80)
turtle.end_fill()
turtle.penup()
turtle.goto(175, -5)
turtle.fillcolor('green')
turtle.begin_fill()
turtle.dot(60)
turtle.end_fill()
turtle.penup()
turtle.goto(135, 35)
turtle.fillcolor('green')
turtle.begin_fill()
turtle.dot(70)
turtle.end_fill()
turtle.penup()

# Правый забор
turtle.pencolor('brown')
turtle.goto(180, -70)
turtle.left(90)
turtle.pendown()
turtle.left(90)
for i in range(3):
    turtle.fillcolor('yellow')
    turtle.begin_fill()
    turtle.forward(40)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(40)
    turtle.end_fill()
    turtle.left(180)
turtle.penup()

# Облака

turtle.pencolor('light blue')
turtle.goto(-170, 160)
turtle.end_fill()
turtle.fillcolor('light blue')
turtle.begin_fill()
turtle.pendown()
turtle.circle(40)
turtle.end_fill()
turtle.penup()

turtle.goto(-220, 150)
turtle.fillcolor('light blue')
turtle.begin_fill()
turtle.pendown()
turtle.circle(40)
turtle.end_fill()
turtle.penup()

turtle.goto(-250, 160)
turtle.fillcolor('light blue')
turtle.begin_fill()
turtle.pendown()
turtle.circle(40)
turtle.end_fill()
turtle.penup()

# Окно
turtle.pencolor('grey')
turtle.goto(-130, -30)
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.pendown()
turtle.forward(50)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

turtle.fillcolor('blue')
turtle.begin_fill()
turtle.left(180)
turtle.forward(50)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

turtle.left(180)
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(20)


turtle.end_fill()

turtle.mainloop()